name: Master_Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ubuntu:
    name: tests_ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@master
      - name: Set up Python ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Resc
        run: bash ./test.sh
