name: Master_Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  name: tests_ubuntu
  runs-on: ubuntu-latest
  steps:
    - run: pip install -r requirements.txt
    - run: bash ./test.sh
